name: hrs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.11
  - pyyaml
  - pandas=2.3.3
  - protobuf
  - flask=3.1.2
  #- gunicorn=23.0.0
  - python-dotenv=1.2.1
  - pyarrow
  - numpy=2.3.3
  - matplotlib=3.10.7
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - gymnasium
  - pillow
  - pip
  - pip:
    - openai==2.9.0
    - google-generativeai==0.8.5
    - chromadb==1.3.5
    - sentence-transformers==5.1.2
    - torch==2.9.1
    - stable-baselines3==2.8.0a2
    - torchvision==0.24.1
    - transformers==4.57.3
    - pyhealth


